let totalCash = parseInt(prompt('how much you got?'))
let watchesCount = parseInt(prompt ('how much watches you want?'))
let earringsCount = parseInt(prompt ('how much earrings you want?'))
let watchesSum = (parseInt(prompt('how much watches costs?')) * watchesCount)
let earringsSum = (parseInt(prompt('how much earrings costs?')) * earringsCount)
let result = totalCash >= (watchesSum + earringsSum)
document.write(result)